# Generated by Django 2.0.8 on 2018-10-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_portals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portals',
            name='title',
        ),
        migrations.DeleteModel(
            name='Portals',
        ),
    ]
