# Generated by Django 2.0.4 on 2018-06-09 14:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('public_date', models.DateTimeField(blank=True, null=True)),
                ('news_texts', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
