# Generated by Django 2.0.8 on 2018-09-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_catalognews_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalognews',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
