# Generated by Django 2.0.8 on 2018-09-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_catalognews_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalognews',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
