# Generated by Django 2.0.8 on 2018-10-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_catalognews_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='catalognews',
            name='status',
            field=models.CharField(choices=[('d', 'Опубликовать'), ('p', 'Редактировать'), ('w', 'Проверить')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='catalognews',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_book', to='news.Category'),
        ),
    ]
