# Generated by Django 2.0.8 on 2018-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181002_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalognews',
            name='public_date',
        ),
        migrations.AddField(
            model_name='catalognews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='catalognews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
