# Generated by Django 2.0.8 on 2018-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalognews',
            name='port',
            field=models.BooleanField(default=False),
        ),
    ]
