# Generated by Django 2.0.8 on 2018-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_catalognews_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalognews',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalognews',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
