# Generated by Django 2.0.8 on 2018-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20181107_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalognews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catalognews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
