# Generated by Django 2.0.8 on 2018-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20181108_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalognews',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
