# Generated by Django 2.0.9 on 2018-11-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20181108_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalognews',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
