# Generated by Django 2.0.8 on 2018-09-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='AboutMe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
