# Generated by Django 2.0.9 on 2018-11-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181121_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
